import Head from "next/head";

import { Text, Box, Link, Flex } from "@chakra-ui/react";

export const Obrigacao = () => {
  return (
    <>
      <Head>
        <title>Quem está obrigado a adotar a RBAC</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Box
        bg={"#fff"}
        w="100%"
        h="auto"
        maxWidth={"7xl"}
        mx="auto"
        my={4}
        px={[4]}
      >
        <Flex
          borderBottom="2px solid"
          borderColor="gray.200"
          alignItems={"center"}
          justifyContent={["center", "center", "space-between"]}
          flexDirection={["column-reverse", "column-reverse", "row"]}
        >
          <Text color={"primary.500"} fontSize={["xl", "2xl"]} my={4}>
            Quem está obrigado a adotar a RBAC?
          </Text>
          <Text color={"gray.400"} alignSelf="flex-end" fontSize={"sm"}>
            <Link href="">Início</Link> / <Link href="">Norma</Link> / Norma
            Quem está obrigado a adotar…
          </Text>
        </Flex>

        <Box my={16}>
          <Text color={"#000"} fontSize={["md"]} textAlign="justify" my={4}>
            Segundo a regulamentação da ANAC (RBAC120), estas medidas se
            estendem a todas as empresas que possuem alguma Atividade de Risco à
            Segurança Operacional (ARSO).
          </Text>
          <Text color={"#000"} fontSize={["md"]} textAlign="justify" my={4}>
            Sendo de responsabilidade de todas as empresas aéreas e prestadoras
            de serviços, a realização de programas explicativos sobre os
            malefícios das drogas, programa de inclusão dos exames nos processos
            admissionais e programa de acompanhamento no caso de um resultado
            positivo.
          </Text>
          <Text color={"primary.500"} fontSize={["xl", "2xl"]} my={4} mt={8}>
            Empresas que se enquadram neste perfil:
          </Text>
          <Text color={"#000"} fontSize={["md"]} textAlign="justify" my={4}>
            <ul>
              <li>serviços públicos especializados;</li>
              <li>empresas de transportes aéreos e serviços especializados;</li>
              <li>empresas despachantes operacionais de voo;</li>
              <li>empresas de combate a incêndios nos aeroportos;</li>
              <li>empresas de segurança aeroportuária;</li>
              <li>
                empresas que desempenhem qualquer atividade que realizada por
                pessoas com acesso ao aeródromo;
              </li>
              <li>
                empresas que realizam manutenção preventiva e corretivas de
                aeronaves, manutenção de produtos de aeronáutica, rádio
                navegação e telecomunicações aeronáuticas;
              </li>
              <li>empresas de transporte de cargas e descargas de bagagens;</li>
              <li>entre outras (…)</li>
            </ul>
          </Text>
          <Text color={"primary.500"} fontSize={["xl", "2xl"]} mt={8}>
            Referência ao Regulamento Brasileiro da Aviação Civil RBAC 120
          </Text>

          <Text
            color={"#000"}
            fontSize={["md"]}
            fontWeight="bold"
            textAlign="justify"
            my={4}
          >
            120.1 Aplicabilidade
          </Text>

          <Text color={"#000"} fontSize={["md"]} textAlign="justify" my={4}>
            (a) Este Regulamento se aplica a qualquer pessoa que desempenhe
            Atividade de Risco à Segurança Operacional na Aviação Civil (ARSO),
            incluindo:
            <ul>
              <li>
                (1) exploradores de serviços aéreos:
                <ul>
                  <li>(i) empresas de transporte aéreo;</li>
                  <li>(ii) serviços aéreos especializados públicos;</li>
                </ul>
              </li>
              <li>
                (2) detentores de certificado sob o RBHA 145, ou RBAC que venha
                a substituí-lo;
              </li>
              <li>(3) detentores de certificado sob o RBAC 139;</li>
              <li>
                (4) empresas subcontratadas, direta ou indiretamente, por
                qualquer dos anteriores para desempenhar ARSO.
              </li>
            </ul>
          </Text>
          <Text color={"#000"} fontSize={["md"]} textAlign="justify" my={4}>
            (b) Para os propósitos deste Regulamento, são consideradas ARSO:
            <ul>
              <li>
                (1) qualquer atividade realizada por uma pessoa, exceto
                passageiro, na área restrita de segurança do aeródromo (ARS);
              </li>
              <li>
                (2) cálculo das posições de carga, bagagem, passageiros e
                combustível nas aeronaves;
              </li>
              <li>
                (3) manutenção, manutenção preventiva e modificações, incluindo
                reparos e inspeções obrigatórias de qualquer dos seguintes
                itens:
                <ul>
                  <li>(i) aeronave;</li>
                  <li>(ii) produtos aeronáuticos;</li>
                  <li>(iii) produtos de radionavegação aeronáutica;</li>
                  <li>(ii) (iv) produtos de telecomunicações aeronáuticas.</li>
                </ul>
              </li>
              <li>
                (4) inspeção e certificação da manutenção de um produto
                mencionado no parágrafo 120.1(b)(3);
              </li>
              <li>
                (5) abastecimento e manutenção dos veículos que serão utilizados
                para o abastecimento das aeronaves na ARS;
              </li>
              <li>
                (6) atividades realizadas por um agente de segurança do
                aeródromo ou um operador de raio-x;
              </li>
              <li>
                (7) atividades realizadas por um membro da tripulação de uma
                aeronave;
              </li>
              <li>
                (8) carga e descarga de veículos de transporte de bagagem
                (trolleys) para carregamento e descarregamento da aeronave e a
                condução destes veículos;
              </li>
              <li>
                (9) atividades de prevenção, salvamento e combate a incêndio.
              </li>
            </ul>
          </Text>

          <Text color={"#000"} fontSize={["md"]} textAlign="justify" my={4}>
            (c) Este Regulamento se aplica a pessoas responsáveis por desempenho
            das ARSO especificadas nos parágrafos 120.1(b)(2) a 120.1(b)(9)
            mesmo que essas atividades não ocorram na ARS.
          </Text>

          <Text
            color={"#000"}
            fontSize={["md"]}
            fontWeight="bold"
            textAlign="justify"
            my={4}
          >
            120.3 Obrigatoriedades
          </Text>

          <Text color={"#000"} fontSize={["md"]} textAlign="justify" my={4}>
            (a) É obrigatória a todas as empresas mencionadas na seção 120.1,
            (Aplicabilidade – exposto acima) à exceção daquelas mencionadas no
            parágrafo 120.1(a)(4), a elaboração, execução e manutenção de um
            Programa de Prevenção do Uso Indevido de Substâncias Psicoativas na
            Aviação Civil (PPSP), bem como de seus subprogramas, todos válidos
            perante a ANAC.
          </Text>
          <Text color={"#000"} fontSize={["md"]} textAlign="justify" my={4}>
            (b) A empresa responsável que seja contratante de outra empresa
            poderá, a seu critério, incluir essa empresa subcontratada no seu
            PPSP, conforme disposto no parágrafo 120.1 (a)(4). Caso opte pela
            não inclusão, deverá exigir que a empresa subcontratada possua seu
            próprio PPSP, igualmente válido perante a ANAC.
          </Text>
          <Text color={"#000"} fontSize={["md"]} textAlign="justify" my={4}>
            (c) Cada empresa responsável deverá apresentar uma declaração de
            conformidade, acompanhada por uma listagem completa de todas as
            seções e requisitos deste Regulamento com o correspondente método de
            conformidade a ser adotado, o que deverá ser entregue à ANAC antes
            da implementação do PPSP proposto.
          </Text>
        </Box>
      </Box>
    </>
  );
};
