import Head from "next/head";

import { Text, Box, Link, Flex } from "@chakra-ui/react";

export const About = () => {
  return (
    <>
      <Head>
        <title>Quem somos - RBAC120</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Box
        bg={"#fff"}
        w="100%"
        h="auto"
        maxWidth={"7xl"}
        mx="auto"
        my={4}
        px={[4]}
      >
        <Flex
          borderBottom="2px solid"
          borderColor="gray.200"
          alignItems={"center"}
          justifyContent={["center", "center", "space-between"]}
          flexDirection={["column-reverse", "column-reverse", "row"]}
        >
          <Text color={"primary.500"} fontSize={["xl", "2xl"]} my={4}>
            Quem somos
          </Text>
          <Text color={"gray.400"} alignSelf="flex-end" fontSize={"sm"}>
            <Link href="">Início</Link> / Quem somos
          </Text>
        </Flex>

        <Box my={16}>
          <Text color={"#000"} fontSize={["md"]} textAlign="justify" my={4}>
            Presentes no Brasil desde 1999 a Toxicologia Pardini é líder de
            exames toxicológicos de larga janela de detecção.
          </Text>
          <Text color={"#000"} fontSize={["md"]} textAlign="justify" my={4}>
            Nossa tecnologia permite avaliar o consumo de drogas mesmo em vários
            meses por amostras de pelos ou cabelos, avaliando seu padrão de
            consumo podendo qualificá-lo de levíssimo a pesadíssimo.
          </Text>
          <Text color={"#000"} fontSize={["md"]} textAlign="justify" my={4}>
            Tecnologia superior em detecção do consumo de drogas, baseadas em
            Radioimunoensaio, associado a tratamento enzimático.
          </Text>
          <Text color={"#000"} fontSize={["md"]} textAlign="justify" my={4}>
            Podendo ser avaliado o consumo de 14 drogas de uma só vez, entre
            elas:
          </Text>
          <Text color={"#000"} fontSize={["md"]} textAlign="justify" my={4}>
            <ul>
              <li>Maconha e derivados (skunk, haxixe…);</li>
              <li>Cocaína e derivados (crack, merla…);</li>
              <li>Ecstasy (MDMA, MDA, MDE);</li>
              <li>Anfetaminas e Metanfetaminas (speed, ice..);</li>
              <li>Heroína, morfina, codeína;</li>
              <li>Oxicodine;</li>
              <li>Hidrocodona;</li>
              <li>Hidromorfina;</li>
              <li>PCP;</li>
              <li>etc.</li>
            </ul>
          </Text>
        </Box>
      </Box>
    </>
  );
};
