import Head from "next/head";
import React from "react";
import { Page } from "src/components/Page";

import type { InferGetStaticPropsType, GetStaticProps } from "next";

import { PageConstructor } from "src/components/PageConstructor";

import { Text, Box, Link, Flex } from "@chakra-ui/react";

const About = ({
  pageTitle,
  texts,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <>
      <Head>
        <title>Quem somos - RBAC120</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Page title={pageTitle} description="Teste1">
        <Box
          bg={"#fff"}
          w="100%"
          h="auto"
          maxWidth={"7xl"}
          mx="auto"
          my={4}
          px={[4]}
        >
          <Flex
            borderBottom="2px solid"
            borderColor="gray.200"
            alignItems={"center"}
            justifyContent={["center", "center", "space-between"]}
            flexDirection={["column-reverse", "column-reverse", "row"]}
          >
            <Text color={"primary.500"} fontSize={["xl", "2xl"]} my={4}>
              {pageTitle}
            </Text>
            <Text color={"gray.400"} alignSelf="flex-end" fontSize={"sm"}>
              <Link href="/">Início</Link> / {pageTitle}
            </Text>
          </Flex>

          <PageConstructor text={texts} />
        </Box>
      </Page>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const pageTitle = "Quem somos";
  const texts = [
    {
      id: "paragraph_01",
      type: "paragraph",
      text: "Presentes no Brasil desde 1999 a Toxicologia Pardini é líder de exames toxicológicos de larga janela de detecção.",
    },
    {
      id: "paragraph_02",
      type: "paragraph",
      text: "Nossa tecnologia permite avaliar o consumo de drogas mesmo em vários meses por amostras de pelos ou cabelos, avaliando seu padrão de consumo podendo qualificá-lo de levíssimo a pesadíssimo.",
    },
    {
      id: "paragraph_03",
      type: "paragraph",
      text: "Tecnologia superior em detecção do consumo de drogas, baseadas em Radioimunoensaio, associado a tratamento enzimático.",
    },
    {
      id: "paragraph_04",
      type: "paragraph",
      text: "Podendo ser avaliado o consumo de 14 drogas de uma só vez, entre elas:",
    },
    {
      id: "list_01",
      type: "iconlist",
      texts: [
        {
          id: "listItem_01",
          type: "listItem",
          text: "Maconha e derivados (skunk, haxixe…);",
        },
        {
          id: "listItem_02",
          type: "listItem",
          text: "Cocaína e derivados (crack, merla…);",
        },
        {
          id: "listItem_03",
          type: "listItem",
          text: "Ecstasy (MDMA, MDA, MDE);",
        },
        {
          id: "listItem_04",
          type: "listItem",
          text: "Anfetaminas e Metanfetaminas (speed, ice..);",
        },
        {
          id: "listItem_05",
          type: "listItem",
          text: "Heroína, morfina, codeína;",
        },
        {
          id: "listItem_06",
          type: "listItem",
          text: "Oxicodine;",
        },
        {
          id: "listItem_07",
          type: "listItem",
          text: "Hidrocodona;",
        },
        {
          id: "listItem_08",
          type: "listItem",
          text: "Hidromorfina;",
        },
        {
          id: "listItem_09",
          type: "listItem",
          text: "PCP;",
        },
        {
          id: "listItem_10",
          type: "listItem",
          text: "etc.",
        },
      ],
    },
  ];

  return {
    props: {
      pageTitle,
      texts,
    },
    revalidate: 60 * 60 * 24, // 24 hours
  };
};

export default About;
