import Head from "next/head";
import React from "react";
import { Page } from "src/components/Page";
import type { InferGetStaticPropsType, GetStaticProps } from "next";
import { ContactForm } from "src/components/ContactForm";
import { Text, Box, Link, Flex } from "@chakra-ui/react";
import { Breadcrumb } from "src/components/Breadcrumb";

const Contact = ({
  pageTitle,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  const breadcrumb = [
    { url: "http://localhost:3000/", name: "Home" },
    { url: "http://localhost:3000/contact", name: "Fale conosco" },
  ];

  return (
    <>
      <Head>
        <title>Fale conosco - RBAC120</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Page title={pageTitle} description="Teste1">
        <Box
          bg={"#fff"}
          w="100%"
          h="auto"
          maxWidth={"7xl"}
          mx="auto"
          my={4}
          px={[4]}
        >
          <Flex
            borderBottom="2px solid"
            borderColor="gray.200"
            alignItems={"center"}
            justifyContent={["center", "center", "space-between"]}
            flexDirection={["column-reverse", "column-reverse", "row"]}
          >
            <Text color={"primary.500"} fontSize={["xl", "2xl"]} my={4}>
              {pageTitle}
            </Text>
            <Text color={"gray.400"} alignSelf="flex-end" fontSize={"sm"}>
              <Link href="/">Início</Link> / {pageTitle}
            </Text>
          </Flex>

          <Breadcrumb breadcrumbItems={breadcrumb} />
          <ContactForm />
        </Box>
      </Page>
    </>
  );
};

//<Breadcrumbs useDefaultStyle rootLabel="Início" />;

export const getStaticProps: GetStaticProps = async () => {
  const pageTitle = "Fale conosco";

  return {
    props: {
      pageTitle,
    },
    revalidate: 60 * 60 * 24, // 24 hours
  };
};

export default Contact;
