import Head from "next/head";
import { Inter } from "@next/font/google";

import { Page } from "src/components/Page";

import { useTopics } from "src/components/Topics/hooks/useTopics";
import { Topics } from "src/components/Topics";

import { useFAQ } from "src/components/FAQ/hooks/useFAQ";
import { FAQ } from "src/components/FAQ";

import { useClients } from "src/components/Clients/hooks/useClients";
import { Clients } from "src/components/Clients";

const inter = Inter({ subsets: ["latin"] });

import { Flex, Text, Image, Box, Link, AspectRatio } from "@chakra-ui/react";

/*
            <AspectRatio ratio={1} maxW="640px">
              <iframe
                src="https://www.youtube.com/embed/W2KIYr2pk7I"
                allowFullScreen
                title="ARSO"
              />
            </AspectRatio>
            */

export default function Home() {
  const { topics } = useTopics();
  const { faq } = useFAQ();
  const { clients } = useClients();

  return (
    <>
      <Head>
        <title>RBAC120 - Norma da ANAC</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Page title="Home" description="Principal">
        <Box bg={"#fff"} w="100%" h="auto">
          <Flex bg="secondary.500" gap={[0, 2, 4]} justifyContent="center">
            <Flex
              w="100%"
              h="auto"
              maxWidth={"7xl"}
              mx="auto"
              px={[0, 0, 4]}
              direction={["column-reverse", "column-reverse", "row"]}
              align={["center", "center", "start"]}
              justifyContent="center"
            >
              <Image
                src="/images/destaque_rbac_120.jpg"
                alt="Destaque RBAC 120."
                objectFit="cover"
                w={["100%", "100%", "auto"]}
                h="100%"
              />

              <Text
                color="#fff"
                fontSize={["xl", "xl", "xl", "3xl"]}
                align={["center", "center", "left"]}
                my={2}
                mx={4}
              >
                Assessoria especializada na implementação da RBAC 120
              </Text>
            </Flex>
          </Flex>

          <Box w="100%" h="auto" maxWidth={"7xl"} mx="auto" my={4} px={[4]}>
            <Text color={"primary.500"} fontSize={["xl", "2xl"]} my={4}>
              Programa de prevenção do uso indevido de substâncias psicoativas
            </Text>
            <Text color={"primary.500"} fontSize={["xl", "2xl"]}>
              Subprograma de educação
            </Text>
            <Text color={"#000"} fontSize={["md"]} textAlign="justify" my={4}>
              De acordo com o RBAC120, todos os funcionários ARSO ou que venham
              a ser admitidos para funções ARSO deverão – obrigatoriamente –
              passar por treinamento e programa educativo. Nosso sistema de
              aprendizagem à distância, e-Learning, atende as exigências e
              apresenta soluções completas com excelente relação custo x
              benefício.
            </Text>
            <Text color={"#000"} fontSize={["md"]} textAlign="justify" my={4}>
              O Sistema de Ensino a Distância (EAD) é formado por 6 módulos que
              podem ser acessados online, por qualquer computador. O curso foi
              criado por especialistas seguindo os requisitos da Norma ANAC.
            </Text>
            <Text color={"#000"} fontSize={["md"]} textAlign="justify" my={4}>
              Assista um clipe representativo de seu conteúdo:
            </Text>
          </Box>

          <Flex
            bg={"#fff"}
            w="100%"
            h="auto"
            maxWidth={"7xl"}
            mx="auto"
            my={4}
            px={[4]}
            flexDirection={["column", "column", "column", "column", "row"]}
          >
            <Box bg="purple" m={"auto"}>
              <iframe
                width="640"
                height="360"
                src="https://www.youtube.com/embed/W2KIYr2pk7I"
                allowFullScreen
                title="ARSO"
              />
            </Box>

            <Box mx="auto" pl={[0, 0, 4]}>
              <Text color={"#000"} fontSize={["md"]} textAlign="justify" my={3}>
                Realizamos o programa necessário para implantação das normas
                exigidas pela RBAC 120.
              </Text>
              <Text color={"primary.500"} fontSize={["xl", "2xl"]}>
                Subprograma de exames toxicológicos
              </Text>
              <Text color={"#000"} fontSize={["md"]} textAlign="justify" my={3}>
                O RBAC 120 estabelece a obrigatoriedade da adoção de um
                subprograma de exames Toxicológicos para Substâncias Psicoativas
                ou ETSP, com regras para garantir a confiabilidade dos exames,
                sua correta aplicação e sua aleatoriedade.
              </Text>
              <Text color={"#000"} fontSize={["md"]} textAlign="justify" my={3}>
                Essa exigência implica na necessidade de uma rede de coleta
                especializada e logística, ferramentas para sorteio e
                administração. Como líderes brasileiros no mercado oferecemos
                todos esses serviços com capilaridade em todo o Brasil.
              </Text>
              <Text color={"#000"} fontSize={["md"]} textAlign="justify" my={3}>
                Saiba mais sobre nossa{" "}
                <Link color="secondary.500" fontWeight="normal" href="/">
                  consultoria de implantação da norma
                </Link>
                .
              </Text>
            </Box>
          </Flex>

          <Topics topics={topics} />

          <FAQ faq={faq} />

          <Clients clients={clients} />
        </Box>
      </Page>
    </>
  );
}
