import Head from "next/head";
import React from "react";
import { Page } from "src/components/Page";

import type { InferGetStaticPropsType, GetStaticProps } from "next";

import { PageConstructor } from "src/components/PageConstructor";

import { Text, Box, Link, Flex } from "@chakra-ui/react";

const Obligation = ({
  pageTitle,
  texts,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <>
      <Head>
        <title>Quem está obrigado a adotar a RBAC? - RBAC120?</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Page title={pageTitle} description="Teste1">
        <Box
          bg={"#fff"}
          w="100%"
          h="auto"
          maxWidth={"7xl"}
          mx="auto"
          my={4}
          px={[4]}
        >
          <Flex
            borderBottom="2px solid"
            borderColor="gray.200"
            alignItems={"center"}
            justifyContent={["center", "center", "space-between"]}
            flexDirection={["column-reverse", "column-reverse", "row"]}
          >
            <Text color={"primary.500"} fontSize={["xl", "2xl"]} my={4}>
              {pageTitle}
            </Text>
            <Text color={"gray.400"} alignSelf="flex-end" fontSize={"sm"}>
              <Link href="/">Início</Link> / {pageTitle}
            </Text>
          </Flex>

          <PageConstructor text={texts} />
        </Box>
      </Page>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const pageTitle = "Quem está obrigado a adotar a RBAC?";
  const texts = [
    {
      id: "paragraph_01",
      type: "paragraph",
      text: "Segundo a regulamentação da ANAC (RBAC120), estas medidas se estendem a todas as empresas que possuem alguma Atividade de Risco à Segurança Operacional (ARSO).",
    },
    {
      id: "paragraph_02",
      type: "paragraph",
      text: "Sendo de responsabilidade de todas as empresas aéreas e prestadoras de serviços, a realização de programas explicativos sobre os malefícios das drogas, programa de inclusão dos exames nos processos admissionais e programa de acompanhamento no caso de um resultado positivo.",
    },
    {
      id: "subtitle_01",
      type: "subtitle",
      text: "Empresas que se enquadram neste perfil:",
    },
    {
      id: "list_01",
      type: "list",
      texts: [
        {
          id: "listItem_01",
          type: "listItem",
          text: "serviços públicos especializados;",
        },
        {
          id: "listItem_02",
          type: "listItem",
          text: "empresas de transportes aéreos e serviços especializados;",
        },
        {
          id: "listItem_03",
          type: "listItem",
          text: "empresas despachantes operacionais de voo;",
        },
        {
          id: "listItem_04",
          type: "listItem",
          text: "empresas de combate a incêndios nos aeroportos;",
        },
        {
          id: "listItem_05",
          type: "listItem",
          text: "empresas de segurança aeroportuária;",
        },
        {
          id: "listItem_06",
          type: "listItem",
          text: "empresas que desempenhem qualquer atividade que realizada por pessoas com acesso ao aeródromo;",
        },
        {
          id: "listItem_07",
          type: "listItem",
          text: "empresas que realizam manutenção preventiva e corretivas de aeronaves, manutenção de produtos de aeronáutica, rádio navegação e telecomunicações aeronáuticas;",
        },
        {
          id: "listItem_08",
          type: "listItem",
          text: "empresas de transporte de cargas e descargas de bagagens;",
        },
        {
          id: "listItem_09",
          type: "listItem",
          text: "entre outras (…)",
        },
      ],
    },
    {
      id: "subtitle_02",
      type: "subtitle",
      text: "Referência ao Regulamento Brasileiro da Aviação Civil RBAC 120",
    },
    {
      id: "paragraph_03",
      type: "paragraphN",
      text: "120.1 Aplicabilidade",
    },
    {
      id: "paragraph_04",
      type: "paragraph",
      text: "(a) Este Regulamento se aplica a qualquer pessoa que desempenhe Atividade de Risco à Segurança Operacional na Aviação Civil (ARSO), incluindo:",
    },
    {
      id: "paragraph_05",
      type: "paragraph",
      text: "(b) Para os propósitos deste Regulamento, são consideradas ARSO:",
    },
    {
      id: "paragraph_06",
      type: "paragraph",
      text: "(c) Este Regulamento se aplica a pessoas responsáveis por desempenho das ARSO especificadas nos parágrafos 120.1(b)(2) a 120.1(b)(9) mesmo que essas atividades não ocorram na ARS.",
    },
    {
      id: "paragraph_07",
      type: "paragraphN",
      text: "120.3 Obrigatoriedades",
    },
    {
      id: "paragraph_08",
      type: "paragraph",
      text: "(a) É obrigatória a todas as empresas mencionadas na seção 120.1, (Aplicabilidade – exposto acima) à exceção daquelas mencionadas no parágrafo 120.1(a)(4), a elaboração, execução e manutenção de um Programa de Prevenção do Uso Indevido de Substâncias Psicoativas na Aviação Civil (PPSP), bem como de seus subprogramas, todos válidos perante a ANAC.",
    },
    {
      id: "paragraph_09",
      type: "paragraph",
      text: "(b) A empresa responsável que seja contratante de outra empresa poderá, a seu critério, incluir essa empresa subcontratada no seu PPSP, conforme disposto no parágrafo 120.1 (a)(4). Caso opte pela não inclusão, deverá exigir que a empresa subcontratada possua seu próprio PPSP, igualmente válido perante a ANAC.",
    },
    {
      id: "paragraph_10",
      type: "paragraph",
      text: "(c) Cada empresa responsável deverá apresentar uma declaração de conformidade, acompanhada por uma listagem completa de todas as seções e requisitos deste Regulamento com o correspondente método de conformidade a ser adotado, o que deverá ser entregue à ANAC antes da implementação do PPSP proposto.",
    },
  ];

  return {
    props: {
      pageTitle,
      texts,
    },
    revalidate: 60 * 60 * 24, // 24 hours
  };
};

export default Obligation;
